tap "charmbracelet/tap"
tap "goreleaser/tap"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "nats-io/nats-tools"
tap "samwho/spacer"

brew "age"
brew "argocd"
brew "python@3.11"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "node"
brew "bash-language-server"
brew "bat"
brew "certstrap"
brew "code-minimap"
brew "coreutils"
brew "croc"
brew "d2"
brew "diff-so-fancy"
brew "direnv"
brew "entr"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "glow"
brew "gnu-getopt"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "golangci-lint"
brew "gopass"
brew "hadolint"
brew "helm"
brew "httpie"
brew "jq"
brew "just"
brew "k9s"
brew "kind"
brew "kubernetes-cli"
brew "krew"
brew "kubectx"
brew "kubeval"
brew "kustomize"
brew "lua-language-server"
brew "make"
brew "mtr"
brew "ncdu"
brew "neovim"
brew "netcat"
brew "onefetch"
brew "pigz"
brew "pinentry-mac"
brew "pre-commit"
brew "pulumi"
brew "pv"
brew "pwgen"
brew "ripgrep"
brew "shellcheck"
brew "shfmt"
brew "starship"
brew "step"
brew "stylua"
brew "tig"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"
brew "yamllint"
brew "yarn"
brew "yq"
brew "zoxide"
brew "zsh"
brew "nats-io/nats-tools/nats"
brew "samwho/spacer/spacer"
cask "font-jetbrains-mono-nerd-font"
cask "gpg-suite"
cask "maccy"
cask "numi"
cask "obsidian"
cask "timer"

vscode "eamodio.gitlens"
vscode "EditorConfig.EditorConfig"
vscode "esbenp.prettier-vscode"
vscode "GitHub.copilot"
vscode "github.vscode-github-actions"
vscode "golang.go"
vscode "jacobdufault.fuzzy-search"
vscode "mkhl.shfmt"
vscode "monokai.theme-monokai-pro-vscode"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.remote-explorer"
vscode "redhat.vscode-yaml"
vscode "rvest.vs-code-prettier-eslint"
vscode "skellock.just"
vscode "Terrastruct.d2"
vscode "Tim-Koehler.helm-intellisense"
vscode "timonwong.shellcheck"
vscode "vscodevim.vim"
vscode "yzhang.markdown-all-in-one"

mas "Bear", id: 1091189122
mas "Caffeinated", id: 1362171212
mas "Codye", id: 1516894961
mas "DaisyDisk", id: 411643860
mas "Gestimer", id: 990588172
mas "iStat Menus", id: 1319778037
mas "Magnet", id: 441258766
mas "SnippetsLab", id: 1006087419
mas "SQLPro for SQLite", id: 586001240
mas "Tomito", id: 1526042938
