#!/usr/bin/env bash
#
# Idea shamelessly stolen from joshua stein:
#   https://github.com/jcs/dotfiles/
#

gh_user="z0mbix"
url="https://github.com/${gh_user}/dotfiles/tarball/master"
os="$(uname)"
tmp_dir="$(mktemp -d XXXXXX)"
tar="tar"
fetch="curl -s -L"

if ! command -v git >/dev/null 2>&1; then
  echo "You need to install git"
  exit 1
fi

# OS Specific Stuff
[ $os == "OpenBSD" ] && fetch="ftp -o -"
[ $os == "SunOS" ] && tar="gtar"

$fetch $url | $tar -C $tmp_dir -xzf -

rm -f $tmp_dir/${gh_user}-*/{README.md,move-in}
cd $tmp_dir/${gh_user}-* && $tar -cf - . | (
  cd
  tar -xf -
)
cd -
rm -rf $tmp_dir

if [ ! -d ~/.ssh/ ]; then
  mkdir ~/.ssh/
  chmod 700 ~/.ssh
fi

if [ ! -f ~/.ssh/authorized_keys ]; then
  touch ~/.ssh/authorized_keys
  chmod 600 ~/.ssh/authorized_keys
fi

if [ $os == "OpenBSD" ]; then
  if [ -f ~/.profile ]; then
    mv ~/.profile ~/.profile.orig
  fi
  mv ~/.profile-openbsd ~/.profile
  rm -f .cshrc .login .mailrc
else
  rm ~/.profile-openbsd ~/.packages.openbsd
fi

if [ ! -d ~/.zsh/completion ]; then
  mkdir -p ~/.zsh/completion
fi

# MacOS specific things
if [ $os == "Darwin" ]; then
  rm -rf ~/.fluxbox
  rm -f ~/.conkyrc .Xdefaults ~/.xsession ~/.xinitrc
  ln -sf ~/.config/Code/User/settings.json ~/Library/Application\ Support/Code/User/settings.json
  ln -sf ~/.config/Code/User/keybindings.json ~/Library/Application\ Support/Code/User/keybindings.json

  if [ -d ~/Library/Mobile\ Documents/com~apple~CloudDocs ] && [ ! -h ~/iCloudDrive ]; then
    ln -s ~/Library/Mobile\ Documents/com~apple~CloudDocs ~/iCloudDrive
  fi

  # install homebrew
  if ! command -v brew >/dev/null 2>&1; then
    echo 'Installing homebrew'
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  echo 'Installing homebrew things'
  brew bundle && rm Brewfile
fi

# Setup shell
[ -f "$HOME/.${SHELL##*/}rc" ] && source "$HOME/.${SHELL##*/}rc"

# Setup vim/neovim
[ ! -d ~/.config/nvim ] && mkdir -p ~/.config/nvim

if command -v nvim >/dev/null 2>&1; then
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  if [ ! -d ~/.local/share/nvim/plugged ]; then
    nvim +PackerInstall +qall
  fi
else
  echo "You need to install neovim"
fi

# Install starship
if ! command -v starship >/dev/null; then
  echo 'installing starship...'
  if [ $os == "Linux" ]; then
    sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- --yes
  fi
  if [ $os == "Darwin" ]; then
    if command -v brew >/dev/null; then
      brew install --quiet starship
    fi
  fi
fi
