add_newline = false

[character]
symbol = "»"

[directory]
truncation_length = 8

[time]
disabled = false
format = "%T"
style = "bold bright-blue"

[kubernetes]
symbol = "⛵ "
style = "bright-purple"
disabled = false

[env_var]
variable = "AWS_CREDS_MSG"
style = "dimmed green"

[java]
disabled = true
