add_newline = false

[character]
format = "$symbol "
success_symbol = "[»](bold green)"
error_symbol = "[»](bold red)"

[directory]
truncation_length = 8

[docker_context]
disabled = true

[username]
format = "[$user]($style) on "

[hostname]
ssh_only = false
style = "bright-green"
format = "[$hostname](bold purple) "

[time]
disabled = false
format = "[$time]($style) "
style = "bold bright-blue"

[aws]
style = "yellow"

[aws.region_aliases]
ap-east-1 = "hkg"
ap-southeast-1 = "sin"
ap-northeast-1 = "tok"
eu-central-1 = "fra"
eu-west-1 = "ire"
eu-west-2 = "lon"
us-east-1 = "n. virg"
us-east-2 = "ohio"
us-west-1 = "cali"

[java]
disabled = true

[kubernetes]
disabled = false
style = "bright-blue"

[python]
style = "bold green"
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[vagrant]
disabled = true

[custom.foo]
command = "tgsrc-status"
files = ["terragrunt.hcl"]
style = "red"
