add_newline = false

[character]
symbol = "»"

[directory]
truncation_length = 8

[hostname]
ssh_only = false
disabled = false

[time]
disabled = false
format = "%T"
style = "bold bright-blue"

[kubernetes]
disabled = false
style = "bright-blue"

[aws.region_aliases]
eu-west-1 = "ire"
eu-west-2 = "lon"

[java]
disabled = true
