add_newline = false

[character]
format = "$symbol "
success_symbol = "[»](bold green)"
error_symbol = "[»](bold red)"

[directory]
truncation_length = 8

[username]
format = "[$user]($style) on "

[hostname]
ssh_only = false
style = "bright-green"
format = "[$hostname](bold green) "

[time]
disabled = false
format = "[$time]($style) "
style = "bold bright-blue"

[kubernetes]
disabled = false
style = "bright-blue"

[aws]
style = "yellow"
#format = '[$symbol($profile )(\($region\) )(\[$duration\])]($style)'

[aws.region_aliases]
ap-southeast-1 = "sin"
eu-central-1 = "fra"
eu-west-1 = "ire"
eu-west-2 = "lon"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[java]
disabled = true

[vagrant]
disabled = true

[custom.foo]
command = "tgsrc-status"
files = ["terragrunt.hcl"]
style = "red"
